### ISSUE TITLE
Players can stop server

### ISSUE THREAD

**Issue by Rotstein007** [Pumpkin-MC/Pumpkin#273]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Linux manjaro

### Server Software Version/Commit

public server

### What happened?

Every player can /stop the server

### To Reproduce

/stop

### Expected behavior

server shouldn't be stoppable from any player

**Comment by Snowiiii** [comment]
Yep, We probably will need to introduce a the Permission system to fix that
