### ISSUE TITLE
Pick block 

### ISSUE THREAD

**Issue by IogaMaster** [Pumpkin-MC/Pumpkin#397]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

There is no support for pick block, sending packet id 34. Without handling it

### Describe the solution you'd like

A functional handling of pick block:
- CREATIVE: Adding the item to the player inventory and placing on the cursor
- SURVIVAL/OTHER MODES: Moving the first stack of that block that is in the inventory to the cursor

**Comment by DataM0del** [comment]
This would be easy.
Also, creative mode doesn't add the item to the player's inventory if the already have that item, in that case, it will just move the first stack of that block that is in the inventory to the cursor, which is what survival mode does

**Comment by Snowiiii** [comment]
Implemented in https://github.com/Pumpkin-MC/Pumpkin/pull/418
